# Generated by Django 3.1.5 on 2021-01-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biography', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biography',
            options={'verbose_name': 'Биография', 'verbose_name_plural': 'Биографии'},
        ),
    ]
