# Generated by Django 3.1.5 on 2021-01-15 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalfordays',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.day'),
        ),
    ]
